xnor_midi: midi.c File Reference
midi.c File Reference
#include "midi.h"
Defines
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
#define NULL 0
Functions
bool midi_is_statusbyte (uint8_t theByte)
bool midi_is_realtime (uint8_t theByte)
midi_packet_length_t midi_packet_length (uint8_t status)
void midi_send_cc (MidiDevice *device, uint8_t chan, uint8_t num, uint8_t val)
void midi_send_noteon (MidiDevice *device, uint8_t chan, uint8_t num, uint8_t vel)
void midi_send_noteoff (MidiDevice *device, uint8_t chan, uint8_t num, uint8_t vel)
void midi_send_aftertouch (MidiDevice *device, uint8_t chan, uint8_t note_num, uint8_t amt)
void midi_send_pitchbend (MidiDevice *device, uint8_t chan, int16_t amt)
void midi_send_programchange (MidiDevice *device, uint8_t chan, uint8_t num)
void midi_send_channelpressure (MidiDevice *device, uint8_t chan, uint8_t amt)
void midi_send_clock (MidiDevice *device)
void midi_send_tick (MidiDevice *device)
void midi_send_start (MidiDevice *device)
void midi_send_continue (MidiDevice *device)
void midi_send_stop (MidiDevice *device)
void midi_send_activesense (MidiDevice *device)
void midi_send_reset (MidiDevice *device)
void midi_send_tcquaterframe (MidiDevice *device, uint8_t time)
void midi_send_songposition (MidiDevice *device, uint16_t pos)
void midi_send_songselect (MidiDevice *device, uint8_t song)
void midi_send_tunerequest (MidiDevice *device)
void midi_send_byte (MidiDevice *device, uint8_t b)
void midi_send_data (MidiDevice *device, uint16_t count, uint8_t byte0, uint8_t byte1, uint8_t byte2)
void midi_register_cc_callback (MidiDevice *device, midi_three_byte_func_t func)
void midi_register_noteon_callback (MidiDevice *device, midi_three_byte_func_t func)
void midi_register_noteoff_callback (MidiDevice *device, midi_three_byte_func_t func)
void midi_register_aftertouch_callback (MidiDevice *device, midi_three_byte_func_t func)
void midi_register_pitchbend_callback (MidiDevice *device, midi_three_byte_func_t func)
void midi_register_songposition_callback (MidiDevice *device, midi_three_byte_func_t func)
void midi_register_progchange_callback (MidiDevice *device, midi_two_byte_func_t func)
void midi_register_chanpressure_callback (MidiDevice *device, midi_two_byte_func_t func)
void midi_register_songselect_callback (MidiDevice *device, midi_two_byte_func_t func)
void midi_register_tc_quarterframe_callback (MidiDevice *device, midi_two_byte_func_t func)
void midi_register_realtime_callback (MidiDevice *device, midi_one_byte_func_t func)
void midi_register_tunerequest_callback (MidiDevice *device, midi_one_byte_func_t func)
void midi_register_sysex_callback (MidiDevice *device, midi_var_byte_func_t func)
void midi_register_fallthrough_callback (MidiDevice *device, midi_var_byte_func_t func)
void midi_register_catchall_callback (MidiDevice *device, midi_var_byte_func_t func)
Define Documentation
#define MIN (x, y) (((x) < (y)) ? (x) : (y))
#define NULL 0
Function Documentation
bool midi_is_realtime (uint8_t theByte)
References MIDI_CLOCK.
Referenced by midi_input_callbacks(), and midi_process_byte().
bool midi_is_statusbyte (uint8_t theByte)
Referenced by midi_process_byte().
midi_packet_length_t midi_packet_length (uint8_t status)
References MIDI_ACTIVESENSE, MIDI_AFTERTOUCH, MIDI_CC, MIDI_CHANPRESSURE, MIDI_CLOCK, MIDI_CONTINUE, MIDI_NOTEOFF, MIDI_NOTEON, MIDI_PITCHBEND, MIDI_PROGCHANGE, MIDI_RESET, MIDI_SONGPOSITION, MIDI_SONGSELECT, MIDI_START, MIDI_STOP, MIDI_TC_QUATERFRAME, MIDI_TICK, MIDI_TUNEREQUEST, SYSEX_BEGIN, and SYSEX_END.
Referenced by midi_process_byte().
void midi_register_aftertouch_callback (MidiDevice * device, midi_three_byte_func_t func)
References _midi_device::input_aftertouch_callback.
void midi_register_catchall_callback (MidiDevice * device, midi_var_byte_func_t func)
References _midi_device::input_catchall_callback.
void midi_register_cc_callback (MidiDevice * device, midi_three_byte_func_t func)
References _midi_device::input_cc_callback.
void midi_register_chanpressure_callback (MidiDevice * device, midi_two_byte_func_t func)
References _midi_device::input_chanpressure_callback.
void midi_register_fallthrough_callback (MidiDevice * device, midi_var_byte_func_t func)
References _midi_device::input_fallthrough_callback.
void midi_register_noteoff_callback (MidiDevice * device, midi_three_byte_func_t func)
References _midi_device::input_noteoff_callback.
void midi_register_noteon_callback (MidiDevice * device, midi_three_byte_func_t func)
References _midi_device::input_noteon_callback.
void midi_register_pitchbend_callback (MidiDevice * device, midi_three_byte_func_t func)
References _midi_device::input_pitchbend_callback.
void midi_register_progchange_callback (MidiDevice * device, midi_two_byte_func_t func)
References _midi_device::input_progchange_callback.
void midi_register_realtime_callback (MidiDevice * device, midi_one_byte_func_t func)
References _midi_device::input_realtime_callback.
void midi_register_songposition_callback (MidiDevice * device, midi_three_byte_func_t func)
References _midi_device::input_songposition_callback.
void midi_register_songselect_callback (MidiDevice * device, midi_two_byte_func_t func)
References _midi_device::input_songselect_callback.
void midi_register_sysex_callback (MidiDevice * device, midi_var_byte_func_t func)
References _midi_device::input_sysex_callback.
void midi_register_tc_quarterframe_callback (MidiDevice * device, midi_two_byte_func_t func)
References _midi_device::input_tc_quaterframe_callback.
void midi_register_tunerequest_callback (MidiDevice * device, midi_one_byte_func_t func)
References _midi_device::input_tunerequest_callback.
void midi_send_activesense (MidiDevice * device)
References MIDI_ACTIVESENSE, and _midi_device::send_func.
void midi_send_aftertouch (MidiDevice * device, uint8_t chan, uint8_t note_num, uint8_t amt)
References MIDI_AFTERTOUCH, MIDI_CHANMASK, and _midi_device::send_func.
void midi_send_byte (MidiDevice * device, uint8_t b)
References _midi_device::send_func.
void midi_send_cc (MidiDevice * device, uint8_t chan, uint8_t num, uint8_t val)
References MIDI_CC, MIDI_CHANMASK, and _midi_device::send_func.
void midi_send_channelpressure (MidiDevice * device, uint8_t chan, uint8_t amt)
References MIDI_CHANMASK, MIDI_CHANPRESSURE, and _midi_device::send_func.
void midi_send_clock (MidiDevice * device)
References MIDI_CLOCK, and _midi_device::send_func.
void midi_send_continue (MidiDevice * device)
References MIDI_CONTINUE, and _midi_device::send_func.
void midi_send_data (MidiDevice * device, uint16_t count, uint8_t byte0, uint8_t byte1, uint8_t byte2)
References _midi_device::send_func.
void midi_send_noteoff (MidiDevice * device, uint8_t chan, uint8_t num, uint8_t vel)
References MIDI_CHANMASK, MIDI_NOTEOFF, and _midi_device::send_func.
void midi_send_noteon (MidiDevice * device, uint8_t chan, uint8_t num, uint8_t vel)
References MIDI_CHANMASK, MIDI_NOTEON, and _midi_device::send_func.
void midi_send_pitchbend (MidiDevice * device, uint8_t chan, int16_t amt)
References MIDI_CHANMASK, MIDI_PITCHBEND, and _midi_device::send_func.
void midi_send_programchange (MidiDevice * device, uint8_t chan, uint8_t num)
References MIDI_CHANMASK, MIDI_PROGCHANGE, and _midi_device::send_func.
void midi_send_reset (MidiDevice * device)
References MIDI_RESET, and _midi_device::send_func.
void midi_send_songposition (MidiDevice * device, uint16_t pos)
References MIDI_SONGPOSITION, and _midi_device::send_func.
void midi_send_songselect (MidiDevice * device, uint8_t song)
References MIDI_SONGSELECT, and _midi_device::send_func.
void midi_send_start (MidiDevice * device)
References MIDI_START, and _midi_device::send_func.
void midi_send_stop (MidiDevice * device)
References MIDI_STOP, and _midi_device::send_func.
void midi_send_tcquaterframe (MidiDevice * device, uint8_t time)
References MIDI_TC_QUATERFRAME, and _midi_device::send_func.
void midi_send_tick (MidiDevice * device)
References MIDI_TICK, and _midi_device::send_func.
void midi_send_tunerequest (MidiDevice * device)
References MIDI_TUNEREQUEST, and _midi_device::send_func.