xnor_midi: midi_device.c File Reference
midi_device.c File Reference
#include "midi_device.h"
#include "midi.h"
Defines
#define NULL 0
Functions
void midi_input_callbacks (MidiDevice *device, uint16_t cnt, uint8_t byte0, uint8_t byte1, uint8_t byte2)
void midi_process_byte (MidiDevice *device, uint8_t input)
void midi_device_init (MidiDevice *device)
void midi_device_input (MidiDevice *device, uint8_t cnt, uint8_t byte0, uint8_t byte1, uint8_t byte2)
void midi_device_set_send_func (MidiDevice *device, midi_var_byte_func_t send_func)
Set the callback function that will be used for sending output data bytes. This is only used if you're creating a custom device. You'll most likely want the callback function to disable interrupts so that you can call the various midi send functions without worrying about locking.
void midi_device_set_pre_input_process_func (MidiDevice *device, midi_no_byte_func_t pre_process_func)
Set a callback which is called at the beginning of the midi_device_process call. This can be used to poll for input data and send the data through the midi_device_input function. You'll probably only use this if you're creating a custom device.
void midi_device_process (MidiDevice *device)
Define Documentation
#define NULL 0
Function Documentation
void midi_device_init (MidiDevice * device)
References _midi_device::input_aftertouch_callback, _midi_device::input_catchall_callback, _midi_device::input_cc_callback, _midi_device::input_chanpressure_callback, _midi_device::input_count, _midi_device::input_fallthrough_callback, _midi_device::input_noteoff_callback, _midi_device::input_noteon_callback, _midi_device::input_pitchbend_callback, _midi_device::input_progchange_callback, _midi_device::input_queue, _midi_device::input_queue_data, _midi_device::input_realtime_callback, _midi_device::input_songposition_callback, _midi_device::input_songselect_callback, _midi_device::input_state, _midi_device::input_sysex_callback, _midi_device::input_tc_quaterframe_callback, _midi_device::input_tunerequest_callback, MIDI_INPUT_QUEUE_LENGTH, and _midi_device::pre_input_process_callback.
void midi_device_input (MidiDevice * device, uint8_t cnt, uint8_t byte0, uint8_t byte1, uint8_t byte2)
References _midi_device::input_queue.
void midi_device_process (MidiDevice * device)
References _midi_device::input_queue, midi_process_byte(), and _midi_device::pre_input_process_callback.
void midi_device_set_pre_input_process_func (MidiDevice * device, midi_no_byte_func_t pre_process_func)
Set a callback which is called at the beginning of the midi_device_process call. This can be used to poll for input data and send the data through the midi_device_input function. You'll probably only use this if you're creating a custom device.
Parameters:
device the midi device to associate this callback with
midi_no_byte_func_t the actual callback function
References _midi_device::pre_input_process_callback.
void midi_device_set_send_func (MidiDevice * device, midi_var_byte_func_t send_func)
Set the callback function that will be used for sending output data bytes. This is only used if you're creating a custom device. You'll most likely want the callback function to disable interrupts so that you can call the various midi send functions without worrying about locking.
Parameters:
device the midi device to associate this callback with
send_func the callback function that will do the sending
References _midi_device::send_func.
void midi_input_callbacks (MidiDevice * device, uint16_t cnt, uint8_t byte0, uint8_t byte1, uint8_t byte2)
References _midi_device::input_aftertouch_callback, _midi_device::input_catchall_callback, _midi_device::input_cc_callback, _midi_device::input_chanpressure_callback, _midi_device::input_fallthrough_callback, _midi_device::input_noteoff_callback, _midi_device::input_noteon_callback, _midi_device::input_pitchbend_callback, _midi_device::input_progchange_callback, _midi_device::input_realtime_callback, _midi_device::input_songposition_callback, _midi_device::input_songselect_callback, _midi_device::input_state, _midi_device::input_sysex_callback, _midi_device::input_tc_quaterframe_callback, _midi_device::input_tunerequest_callback, MIDI_AFTERTOUCH, MIDI_CC, MIDI_CHANPRESSURE, midi_is_realtime(), MIDI_NOTEOFF, MIDI_NOTEON, MIDI_PITCHBEND, MIDI_PROGCHANGE, MIDI_SONGPOSITION, MIDI_SONGSELECT, MIDI_TC_QUATERFRAME, MIDI_TUNEREQUEST, and SYSEX_MESSAGE.
Referenced by midi_process_byte().
void midi_process_byte (MidiDevice * device, uint8_t input)
References IDLE, _midi_device::input_buffer, _midi_device::input_count, _midi_device::input_state, midi_input_callbacks(), midi_is_realtime(), midi_is_statusbyte(), midi_packet_length(), ONE, SYSEX_BEGIN, SYSEX_END, SYSEX_MESSAGE, THREE, TWO, TWO_BYTE_MESSAGE, and UNDEFINED.
Referenced by midi_device_process().